spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phishing_db
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379