spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phishing_db
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

  # Day 9 Mail Configuration (Fixes JavaMailSender Startup Crash)
  mail:
    host: localhost
    port: 25
    username: test-user
    password: test-password
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

# Day 10 Update: Operational Metrics and Monitoring (Root level)
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always
      # Day 10 Optimization: Disables mail health check indicator so dummy mail won't mark application DOWN
  health:
    status:
      order: "UP, DOWN"
    mail:
      enabled: false